### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by team-penguin** [jonathanopalise/ppengine#1]
In file included from src/scene/scene.c:3:0:
src/scene/osg/scene.h:6:10: fatal error: osgGA/GUIEventHandler: No such file or directory
 #include <osgGA/GUIEventHandler>

Thank you in advance.

**Comment by jonathanopalise** [comment]
Hi, do you have the dev libraries for openscenegraph installed?

The package is called libopenscenegraph-dev on Ubuntu.

**Comment by team-penguin** [comment]
I'm getting further now, thanks. I think I'm using the wrong version of
OpenSceneGraph:

In file included from src/input/input.c:3:0:
src/input/keyboard_handler.h:9:30: error: 'osgGA::GUIEventHandlerVisitor'
has not been declared
   virtual void accept(osgGA::GUIEventHandlerVisitor& v)   {
v.visit(*this); };

I've tried 3.4.1 and 3.5.5, what is the correct version?

**Comment by jonathanopalise** [comment]
I'm using 3.2.3 here. I've done a bit of reading and it looks like the GUIEventHandlerVisitor class may have been removed from newer versions of OSG.

**Comment by team-penguin** [comment]
Success! Thank you for the help and port.
